apiVersion: v1
kind: ServiceAccount
metadata:
  name: resume-builder-api
  namespace: resume-builder
  labels:
    app: api
    app.kubernetes.io/name: api
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: resume-builder
