apiVersion: v1
kind: ServiceAccount
metadata:
  name: resume-builder-frontend
  namespace: resume-builder
  labels:
    app: frontend
    app.kubernetes.io/name: frontend
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: resume-builder
