apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: worker-pdb
  namespace: resume-builder
  labels:
    app: worker
    app.kubernetes.io/name: worker
    app.kubernetes.io/component: worker
    app.kubernetes.io/part-of: resume-builder
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: worker
