apiVersion: v1
kind: ServiceAccount
metadata:
  name: resume-builder-worker
  namespace: resume-builder
  labels:
    app: worker
    app.kubernetes.io/name: worker
    app.kubernetes.io/component: worker
    app.kubernetes.io/part-of: resume-builder
